#!/bin/bash -eu

tag="snap.$SNAP_INSTANCE_NAME.hook.post-refresh"
exec 1> >(tee >(logger --tag=$tag))
exec 2> >(logger --stderr --priority error --tag=$tag)

if snapctl is-connected hardware-observe; then
    modelctl use-engine --fix --assume-yes --verbose
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --fix --assume-yes --verbose
else
    echo "hardware-observe interface not connected. Skip fixing the active engine."
fi
